### ISSUE TITLE
"Board not supported" 4.3" ESP32-8048S043C

### ISSUE THREAD

**Issue by dkGoodrich** [suchmememanyskill/CYD-Klipper#96] opened 2024-05-02 06:01 UTC
Hi, I bought this board to work with your CYD-Klipper and its giving me this error

Thank you for your time, 
DK

Amazon link below

https://www.amazon.com/DIYmalls-ESP32-8048S043C-I-Capacitive-ESP32-S3-WROOM-1-Development/dp/B0CLGCMWQ7/ref=sr_1_1?crid=1XUI84WJ9HAAD&dib=eyJ2IjoiMSJ9._wN8V7wg6pAZNqZDYFhMrFDvQRUkMxzz1RRIyzVcK0rmtLUOP_npWDg_Z_n_g7CNtvngnaSEBGfZhT7Rhv3QEGQdJ60e7l4OBY8rmPL0k-93DmvLXlAFQCrf-TDmQoNTYf3f5P_pMWB5Iyomqg0MeiiIEB_3z1Skty5PkUEOoYE.32RcXr4GBDmXZ0zLSaHl0IEjZyhdIfSqTG6vYz0rYls&dib_tag=se&keywords=esp32-8048s043c-i&qid=1714629570&sprefix=esp32-8048s043c-i%2Caps%2C82&sr=8-1

**Comment by suchmememanyskill** [comment] 2024-05-02 07:12
Duplicate of #67

For now install via platformio: https://github.com/suchmememanyskill/CYD-Klipper/blob/dev/Manual_Install.md#building--flashing-via-platformio

**Closed** 2024-05-25 22:35 UTC
