### ISSUE TITLE
Printer power switch (mainsail)

### ISSUE THREAD

**Issue by AndreyShpilevoy** [suchmememanyskill/CYD-Klipper#21] opened 2024-01-30 23:23 UTC
Hi,
I found that if Klipper returns an error - CYD will display it as well as the buttons `Restart `and `Restart Firmware`.
But if I enable the Printer power switch (mainsail) functionality - CYD just trying continuously to reconnect to Klipper.

More details about functionality:
https://docs.mainsail.xyz/overview/quicktips/printer-power-switch

![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/8218452/85db8446-387b-4a70-8e72-6b6a427b3fb0)

Is it possible to implement an extra mode on CYD to easily Power On the printer with the single button if this functionality is enabled on the host?

**Comment by suchmememanyskill** [comment] 2024-01-31 06:02
Duplicate of #20

**Closed** 2024-01-31 06:02 UTC
